language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"

env:
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9

install:
  - pip install django==$DJANGO_VERSION
  - pip install .

script:
  - python setup.py test
